import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Linking,
  Share,
  Alert,
  ScrollView,
} from 'react-native';
import { useTranslation } from 'react-i18next';
import { useTheme } from '../../contexts/ThemeContext';
import { typography } from '../../theme/typography';
import { spacing, borderRadius } from '../../theme/spacing';
import { WEB_BASE_URL } from '../../config/env';

interface Props {
  title: string;
  audioUrl: string;
  duration?: string;
  script?: string;
  onClose?: () => void;
}

const PLAYBACK_RATES = ['1x', '1.25x', '1.5x', '1.75x', '2x'];

export default function PodcastPlayer({ title, audioUrl, duration, script, onClose }: Props) {
  const { t } = useTranslation();
  const { theme } = useTheme();
  const [showScript, setShowScript] = useState(false);
  const [selectedRate, setSelectedRate] = useState(0);

  const handlePlay = async () => {
    try {
      const canOpen = await Linking.canOpenURL(audioUrl);
      if (canOpen) {
        await Linking.openURL(audioUrl);
      } else {
        Alert.alert('', t('cannotOpenAudio', 'Nao foi possivel abrir o audio.'));
      }
    } catch {
      Alert.alert('', t('cannotOpenAudio', 'Nao foi possivel abrir o audio.'));
    }
  };

  const handleShare = async () => {
    try {
      await Share.share({
        title,
        message: `${title}\n${audioUrl}`,
        url: audioUrl,
      });
    } catch {}
  };

  const handleShareScript = async () => {
    if (!script) return;
    const footer = `\n---\nGenerated by Qython\n${WEB_BASE_URL}`;
    try {
      await Share.share({
        title,
        message: `# ${title}\n\n${script}${footer}`,
      });
    } catch {}
  };

  const wordCount = script ? script.split(/\s+/).length : 0;
  const estMinutes = Math.ceil(wordCount / 150);

  return (
    <View style={[styles.container, { backgroundColor: theme.surface, borderColor: theme.surfaceBorder }]}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.iconContainer}>
          <Text style={styles.icon}>{'\uD83C\uDF99\uFE0F'}</Text>
        </View>
        <View style={styles.info}>
          <Text style={[styles.title, { color: theme.text }]} numberOfLines={2}>
            {title}
          </Text>
          <View style={styles.metaRow}>
            {duration && (
              <Text style={[styles.metaText, { color: theme.textMuted }]}>
                {duration}
              </Text>
            )}
            {wordCount > 0 && (
              <Text style={[styles.metaText, { color: theme.textMuted }]}>
                {wordCount} {t('words', 'palavras')} ({'\u2248'}{estMinutes}min)
              </Text>
            )}
          </View>
        </View>
        {onClose && (
          <TouchableOpacity onPress={onClose} style={styles.closeBtn}>
            <Text style={[styles.closeBtnText, { color: theme.textMuted }]}>
              {'\u2715'}
            </Text>
          </TouchableOpacity>
        )}
      </View>

      {/* Playback speed selector */}
      <View style={styles.speedRow}>
        <Text style={[styles.speedLabel, { color: theme.textMuted }]}>
          {t('playbackSpeed', 'Velocidade')}:
        </Text>
        <View style={styles.speedPills}>
          {PLAYBACK_RATES.map((rate, idx) => (
            <TouchableOpacity
              key={rate}
              style={[
                styles.speedPill,
                { borderColor: idx === selectedRate ? theme.primary : theme.surfaceBorder },
                idx === selectedRate && { backgroundColor: `${theme.primary}15` },
              ]}
              onPress={() => setSelectedRate(idx)}>
              <Text style={[
                styles.speedPillText,
                { color: idx === selectedRate ? theme.primary : theme.textMuted },
              ]}>
                {rate}
              </Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      {/* Actions */}
      <View style={styles.actions}>
        <TouchableOpacity
          style={[styles.playBtn, { backgroundColor: theme.primary }]}
          onPress={handlePlay}
          activeOpacity={0.8}>
          <Text style={styles.playBtnIcon}>{'\u25B6'}</Text>
          <Text style={styles.playBtnText}>
            {t('playPodcast', 'Ouvir Podcast')}
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.shareBtn, { borderColor: theme.surfaceBorder }]}
          onPress={handleShare}
          activeOpacity={0.8}>
          <Text style={[styles.shareBtnText, { color: theme.primary }]}>
            {t('downloadMaterial', 'Compartilhar')}
          </Text>
        </TouchableOpacity>
      </View>

      {/* Script toggle + content */}
      {script && (
        <>
          <TouchableOpacity
            style={[styles.scriptToggle, { borderTopColor: theme.surfaceBorder }]}
            onPress={() => setShowScript(!showScript)}>
            <Text style={[styles.scriptToggleText, { color: theme.primary }]}>
              {showScript ? t('hideScript', 'Ocultar Script') : t('showScript', 'Ver Script')}
            </Text>
            <Text style={[styles.scriptToggleIcon, { color: theme.primary }]}>
              {showScript ? '\u25B2' : '\u25BC'}
            </Text>
          </TouchableOpacity>

          {showScript && (
            <View style={styles.scriptSection}>
              <ScrollView style={styles.scriptScroll} nestedScrollEnabled>
                <Text style={[styles.scriptText, { color: theme.textSecondary }]}>
                  {script}
                </Text>
              </ScrollView>
              <TouchableOpacity
                style={[styles.exportScriptBtn, { borderColor: theme.surfaceBorder }]}
                onPress={handleShareScript}>
                <Text style={[styles.exportScriptText, { color: theme.primary }]}>
                  {t('exportScript', 'Exportar Script')}
                </Text>
              </TouchableOpacity>
            </View>
          )}
        </>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.base,
    marginBottom: spacing.md,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  iconContainer: {
    width: 48, height: 48, borderRadius: borderRadius.md,
    backgroundColor: 'rgba(187, 134, 252, 0.15)',
    justifyContent: 'center', alignItems: 'center', marginRight: spacing.md,
  },
  icon: { fontSize: 24 },
  info: { flex: 1 },
  title: { ...typography.label, fontWeight: '600' },
  metaRow: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.xs },
  metaText: { ...typography.caption },
  closeBtn: { padding: spacing.sm },
  closeBtnText: { fontSize: 16, fontWeight: '600' },
  speedRow: {
    flexDirection: 'row', alignItems: 'center', marginBottom: spacing.md, gap: spacing.sm,
  },
  speedLabel: { ...typography.caption },
  speedPills: { flexDirection: 'row', gap: spacing.xs },
  speedPill: {
    paddingHorizontal: spacing.sm, paddingVertical: 4,
    borderRadius: borderRadius.full, borderWidth: 1,
  },
  speedPillText: { ...typography.caption, fontWeight: '600' },
  actions: { flexDirection: 'row', gap: spacing.sm },
  playBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    paddingVertical: spacing.md, borderRadius: borderRadius.md, gap: spacing.sm,
  },
  playBtnIcon: { color: '#fff', fontSize: 14 },
  playBtnText: { ...typography.buttonSmall, color: '#fff' },
  shareBtn: {
    flex: 1, alignItems: 'center', justifyContent: 'center',
    paddingVertical: spacing.md, borderRadius: borderRadius.md, borderWidth: 1,
  },
  shareBtnText: { ...typography.buttonSmall },
  scriptToggle: {
    flexDirection: 'row', justifyContent: 'center', alignItems: 'center',
    marginTop: spacing.md, paddingTop: spacing.md, borderTopWidth: 1, gap: spacing.sm,
  },
  scriptToggleText: { ...typography.buttonSmall },
  scriptToggleIcon: { fontSize: 10 },
  scriptSection: { marginTop: spacing.sm },
  scriptScroll: { maxHeight: 200 },
  scriptText: { ...typography.bodySmall, lineHeight: 22 },
  exportScriptBtn: {
    alignItems: 'center', paddingVertical: spacing.sm, marginTop: spacing.sm,
    borderRadius: borderRadius.md, borderWidth: 1,
  },
  exportScriptText: { ...typography.buttonSmall },
});
