import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  Modal,
  ScrollView,
  TouchableOpacity,
  Alert,
  Share,
} from 'react-native';
import Clipboard from '@react-native-clipboard/clipboard';
import { useTranslation } from 'react-i18next';
import { useTheme } from '../../contexts/ThemeContext';
import { typography } from '../../theme/typography';
import { spacing, borderRadius } from '../../theme/spacing';
import { deleteConsultations, downloadAndSharePdf } from '../../services/ambulatory';
import type { Consultation } from '../../types/ambulatory';
import { WEB_BASE_URL } from '../../config/env';

interface Props {
  visible: boolean;
  consultation: Consultation | null;
  onClose: () => void;
  onDeleted: (id: number) => void;
  onShare?: (consultation: Consultation) => void;
}

export default function ConsultationDetailModal({
  visible,
  consultation,
  onClose,
  onDeleted,
  onShare,
}: Props) {
  const { t } = useTranslation();
  const { theme } = useTheme();

  if (!consultation) return null;

  const date = new Date(consultation.created_at).toLocaleDateString();
  const typeLabel = consultation.is_first_consultation
    ? t('firstConsultation', 'Primeira Consulta')
    : t('returnConsultation', 'Retorno');

  const getExportContent = (section?: 'improved' | 'summary') => {
    if (section === 'improved') return consultation.improved_notes || consultation.raw_notes;
    if (section === 'summary') return consultation.summary || '';
    // Full consultation
    const parts = [
      `${t('specialty', 'Especialidade')}: ${consultation.specialty}`,
      consultation.patient_name ? `${t('patient', 'Paciente')}: ${consultation.patient_name}` : '',
      `${t('date', 'Data')}: ${date}`,
      '',
      consultation.improved_notes
        ? `## ${t('improvedNotes', 'Notas Aprimoradas')}\n${consultation.improved_notes}`
        : `## ${t('rawNotes', 'Notas Originais')}\n${consultation.raw_notes}`,
      consultation.summary ? `\n## ${t('summary', 'Resumo')}\n${consultation.summary}` : '',
    ];
    return parts.filter(Boolean).join('\n');
  };

  const handleExportAs = (format: 'txt' | 'md' | 'pdf' | 'copy') => {
    const content = getExportContent();
    const footer = `\n---\nGenerated by Qython\n${WEB_BASE_URL}\n${new Date().toLocaleString()}`;

    if (format === 'copy') {
      Clipboard.setString(content);
      Alert.alert('', t('messageCopied', 'Copiado!'));
      return;
    }
    if (format === 'pdf') {
      const mdContent = content;
      downloadAndSharePdf(
        `/export/pdf`,
        `Consulta_${consultation.specialty.replace(/\s+/g, '_')}.pdf`,
      ).catch(() => {});
      return;
    }
    // TXT or MD — use native share
    const text = format === 'md'
      ? `# ${t('consultation', 'Consulta')} - ${consultation.specialty}\n\n${content}${footer}`
      : content + footer;
    Share.share({
      title: `${t('consultation', 'Consulta')} - ${consultation.specialty}`,
      message: text,
    }).catch(() => {});
  };

  const handleShareMenu = () => {
    Alert.alert(
      t('share', 'Compartilhar'),
      '',
      [
        { text: t('copyToClipboard', 'Copiar'), onPress: () => handleExportAs('copy') },
        { text: t('shareAsTxtLabel', 'Texto (.txt)'), onPress: () => handleExportAs('txt') },
        { text: t('shareAsMdLabel', 'Markdown (.md)'), onPress: () => handleExportAs('md') },
        { text: t('cancel', 'Cancelar'), style: 'cancel' },
      ],
    );
  };

  const handleDelete = () => {
    Alert.alert(
      t('deleteConsultation', 'Excluir Consulta'),
      t('deleteConsultationConfirm', 'Tem certeza que deseja excluir esta consulta?'),
      [
        { text: t('cancel', 'Cancelar'), style: 'cancel' },
        {
          text: t('delete', 'Excluir'),
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteConsultations([consultation.id]);
              onDeleted(consultation.id);
              onClose();
            } catch {
              Alert.alert('', t('errorDeletingConsultation', 'Erro ao excluir consulta'));
            }
          },
        },
      ],
    );
  };

  const renderSection = (title: string, content: string | null) => {
    if (!content) return null;
    return (
      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: theme.text }]}>{title}</Text>
        <View style={[styles.contentBox, { backgroundColor: theme.surface, borderColor: theme.surfaceBorder }]}>
          <Text style={[styles.contentText, { color: theme.textSecondary }]}>{content}</Text>
        </View>
      </View>
    );
  };

  return (
    <Modal visible={visible} animationType="slide" onRequestClose={onClose}>
      <View style={[styles.container, { backgroundColor: theme.background }]}>
        {/* Header */}
        <View style={[styles.header, { borderBottomColor: theme.surfaceBorder }]}>
          <TouchableOpacity onPress={onClose}>
            <Text style={[styles.headerButton, { color: theme.textMuted }]}>
              {t('close', 'Fechar')}
            </Text>
          </TouchableOpacity>
          <Text style={[styles.headerTitle, { color: theme.text }]}>
            {consultation.specialty}
          </Text>
          <View style={{ flexDirection: 'row', gap: 12 }}>
            <TouchableOpacity onPress={handleShareMenu}>
              <Text style={[styles.headerButton, { color: theme.primary }]}>
                {t('share', 'Compartilhar')}
              </Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={handleDelete}>
              <Text style={[styles.headerButton, { color: '#e74c3c' }]}>
                {t('delete', 'Excluir')}
              </Text>
            </TouchableOpacity>
          </View>
        </View>

        <ScrollView contentContainerStyle={styles.scrollContent}>
          {/* Meta info */}
          <View style={[styles.metaCard, { backgroundColor: theme.surface, borderColor: theme.surfaceBorder }]}>
            <View style={styles.metaRow}>
              <Text style={[styles.metaLabel, { color: theme.textMuted }]}>
                {t('date', 'Data')}
              </Text>
              <Text style={[styles.metaValue, { color: theme.text }]}>{date}</Text>
            </View>
            <View style={styles.metaRow}>
              <Text style={[styles.metaLabel, { color: theme.textMuted }]}>
                {t('consultationType', 'Tipo')}
              </Text>
              <Text style={[styles.metaValue, { color: theme.text }]}>{typeLabel}</Text>
            </View>
            {consultation.patient_name && (
              <View style={styles.metaRow}>
                <Text style={[styles.metaLabel, { color: theme.textMuted }]}>
                  {t('patient', 'Paciente')}
                </Text>
                <Text style={[styles.metaValue, { color: theme.text }]}>
                  {consultation.patient_name}
                </Text>
              </View>
            )}
            {consultation.duration_minutes != null && (
              <View style={styles.metaRow}>
                <Text style={[styles.metaLabel, { color: theme.textMuted }]}>
                  {t('duration', 'Duracao')}
                </Text>
                <Text style={[styles.metaValue, { color: theme.text }]}>
                  {consultation.duration_minutes} min
                </Text>
              </View>
            )}
          </View>

          {renderSection(t('rawNotes', 'Notas Originais'), consultation.raw_notes)}
          {renderSection(t('improvedNotes', 'Notas Aprimoradas'), consultation.improved_notes)}
          {renderSection(t('summary', 'Resumo'), consultation.summary)}
        </ScrollView>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
  },
  headerTitle: {
    ...typography.body,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
  },
  headerButton: {
    ...typography.body,
  },
  scrollContent: {
    padding: spacing.base,
    paddingBottom: spacing.xxl,
  },
  metaCard: {
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.base,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: spacing.xs,
  },
  metaLabel: {
    ...typography.bodySmall,
  },
  metaValue: {
    ...typography.bodySmall,
    fontWeight: '500',
  },
  section: {
    marginTop: spacing.lg,
  },
  sectionTitle: {
    ...typography.h3,
    marginBottom: spacing.md,
  },
  contentBox: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    padding: spacing.base,
  },
  contentText: {
    ...typography.body,
    lineHeight: 24,
  },
});
