"""add_surgical_center_models

Revision ID: 29185922f924
Revises: c9e12556e842
Create Date: 2026-01-03 05:49:09.039668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29185922f924'
down_revision = 'c9e12556e842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surgical_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('patient_weight', sa.Float(), nullable=False),
    sa.Column('patient_height', sa.Float(), nullable=True),
    sa.Column('patient_gender', sa.String(length=20), nullable=True),
    sa.Column('patient_comorbidities', sa.JSON(), nullable=True),
    sa.Column('patient_allergies', sa.JSON(), nullable=True),
    sa.Column('patient_medications', sa.JSON(), nullable=True),
    sa.Column('asa_score', sa.Integer(), nullable=True),
    sa.Column('mallampati_score', sa.Integer(), nullable=True),
    sa.Column('goldman_score', sa.Integer(), nullable=True),
    sa.Column('airways_difficulty_predicted', sa.Boolean(), nullable=True),
    sa.Column('procedure_name', sa.String(length=255), nullable=False),
    sa.Column('procedure_specialty', sa.String(length=100), nullable=True),
    sa.Column('procedure_urgency', sa.String(length=20), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=50), nullable=True),
    sa.Column('surgeon_name', sa.String(length=255), nullable=True),
    sa.Column('anesthesiologist_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('generated_report', sa.Text(), nullable=True),
    sa.Column('final_report', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('drug_name', sa.String(length=100), nullable=False),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.Column('dose_unit', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('was_suggested', sa.Boolean(), nullable=True),
    sa.Column('suggested_dose', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['surgical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['surgical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgical_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('had_difficult_airway', sa.Boolean(), nullable=True),
    sa.Column('had_hypotension', sa.Boolean(), nullable=True),
    sa.Column('had_hypertension', sa.Boolean(), nullable=True),
    sa.Column('had_bradycardia', sa.Boolean(), nullable=True),
    sa.Column('had_tachycardia', sa.Boolean(), nullable=True),
    sa.Column('had_desaturation', sa.Boolean(), nullable=True),
    sa.Column('had_bleeding', sa.Boolean(), nullable=True),
    sa.Column('had_conversion', sa.Boolean(), nullable=True),
    sa.Column('had_unplanned_icu', sa.Boolean(), nullable=True),
    sa.Column('had_awareness', sa.Boolean(), nullable=True),
    sa.Column('had_nausea_vomiting', sa.Boolean(), nullable=True),
    sa.Column('blood_loss_ml', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('outcome_class', sa.String(length=30), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['surgical_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surgical_outcomes')
    op.drop_table('surgical_events')
    op.drop_table('drug_administrations')
    op.drop_table('surgical_cases')
    # ### end Alembic commands ###
