"""add_user_kyc_fields

Revision ID: 2dd2b12da717
Revises: 683707f901f9
Create Date: 2025-12-22 20:34:31.444545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd2b12da717'
down_revision = '683707f901f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
