"""add_payment_fields_v2

Revision ID: 3607466dfac0
Revises: c027e92508fc
Create Date: 2025-11-28 00:01:08.721760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3607466dfac0'
down_revision = 'c027e92508fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
