"""Change exam title and description to translation keys

Revision ID: 5f425e5a139e
Revises: eece5ae4aa41
Create Date: 2025-11-06 21:12:07.326854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f425e5a139e'
down_revision = 'eece5ae4aa41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_exams', sa.Column('title_key', sa.String(length=100), nullable=False))
    op.add_column('arena_exams', sa.Column('description_key', sa.Text(), nullable=True))
    op.drop_column('arena_exams', 'description')
    op.drop_column('arena_exams', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_exams', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('arena_exams', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('arena_exams', 'description_key')
    op.drop_column('arena_exams', 'title_key')
    # ### end Alembic commands ###
