"""add_user_kyc_fields

Revision ID: 683707f901f9
Revises: 900f363345c7
Create Date: 2025-12-22 16:20:02.117348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683707f901f9'
down_revision = '900f363345c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('proof_document_path', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('verification_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_notes')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'proof_document_path')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
