"""Add phone_verified column

Revision ID: 720894c0bc36
Revises: 2dd2b12da717
Create Date: 2025-12-23 15:50:41.312918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720894c0bc36'
down_revision = '2dd2b12da717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
