"""add_marketing_consent

Revision ID: 784aaa0d5fea
Revises: e01c41dd4579
Create Date: 2025-12-28 01:37:16.628897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784aaa0d5fea'
down_revision = 'e01c41dd4579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('marketing_consent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_consent')
    # ### end Alembic commands ###
