"""Add user preferences and anamnesis templates

Revision ID: 834f5f01008f
Revises: c1af2f0502ac
Create Date: 2025-06-01 18:34:47.303122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834f5f01008f'
down_revision = 'c1af2f0502ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_anamnesis_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('consultation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'specialty', 'consultation_type', name='_user_specialty_consultation_uc')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('language_preference', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language_preference')
        batch_op.drop_column('theme_preference')

    op.drop_table('user_anamnesis_templates')
    # ### end Alembic commands ###
