"""fix_invitation_model

Revision ID: 900f363345c7
Revises: 3607466dfac0
Create Date: 2025-11-28 04:48:17.051693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900f363345c7'
down_revision = '3607466dfac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('used_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('invitations_token_key'), 'invitations', type_='unique')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.drop_constraint(op.f('invitations_user_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'users', ['used_by_user_id'], ['id'])
    op.drop_column('invitations', 'filename')
    op.drop_column('invitations', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invitations', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_user_id_fkey'), 'invitations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_unique_constraint(op.f('invitations_token_key'), 'invitations', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('invitations', 'used_by_user_id')
    # ### end Alembic commands ###
