"""add progress tracking fields to podcast and video jobs

Revision ID: 9abc06438de2
Revises: 2026_01_12_materials
Create Date: 2026-01-13 03:10:12.454449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9abc06438de2'
down_revision = '2026_01_12_materials'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_summaries_session_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.add_column('podcast_generation_jobs', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.add_column('podcast_generation_jobs', sa.Column('current_step', sa.String(length=100), nullable=True))
    op.add_column('podcast_generation_jobs', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('podcast_generation_jobs', sa.Column('completed_chunks', sa.Integer(), nullable=True))
    op.alter_column('surgical_templates', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.add_column('video_lesson_jobs', sa.Column('srt_path', sa.String(length=500), nullable=True))
    op.add_column('video_lesson_jobs', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.add_column('video_lesson_jobs', sa.Column('current_step', sa.String(length=100), nullable=True))
    op.add_column('video_lesson_jobs', sa.Column('total_steps', sa.Integer(), nullable=True))
    op.add_column('video_lesson_jobs', sa.Column('completed_steps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_lesson_jobs', 'completed_steps')
    op.drop_column('video_lesson_jobs', 'total_steps')
    op.drop_column('video_lesson_jobs', 'current_step')
    op.drop_column('video_lesson_jobs', 'progress_percent')
    op.drop_column('video_lesson_jobs', 'srt_path')
    op.alter_column('surgical_templates', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('podcast_generation_jobs', 'completed_chunks')
    op.drop_column('podcast_generation_jobs', 'total_chunks')
    op.drop_column('podcast_generation_jobs', 'current_step')
    op.drop_column('podcast_generation_jobs', 'progress_percent')
    op.create_table('conversation_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('messages_up_to', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('conversation_summaries_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_summaries_pkey'))
    )
    op.create_index(op.f('ix_conversation_summaries_session_id'), 'conversation_summaries', ['session_id'], unique=False)
    # ### end Alembic commands ###
