"""Initial database setup with all tables

Revision ID: b55e0451ef24
Revises: 
Create Date: 2025-05-21 19:56:34.872818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b55e0451ef24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('is_first_consultation', sa.Boolean(), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=False),
    sa.Column('improved_notes', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('identifier_type', sa.String(length=50), nullable=True),
    sa.Column('identifier_number', sa.String(length=50), nullable=True),
    sa.Column('referral_source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dracmas', sa.Float(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('avatar_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Resquício do yoyo-migrations, usado antes do Alembic. O --autogenerate
    # rodou contra um banco que ainda tinha essas tabelas e emitiu drop_table
    # incondicional — que funciona ao migrar um banco antigo e falha com
    # UndefinedTable em qualquer banco novo, onde elas nunca existiram.
    # Com IF EXISTS a limpeza continua valendo para quem vem do yoyo, e uma
    # instalação do zero passa.
    for _legacy in ('yoyo_lock', '_yoyo_version', '_yoyo_migration', '_yoyo_log'):
        op.execute(f'DROP TABLE IF EXISTS {_legacy}')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_yoyo_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('migration_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('migration_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='_yoyo_log_pkey')
    )
    op.create_table('_yoyo_migration',
    sa.Column('migration_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('migration_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('applied_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('migration_hash', name='_yoyo_migration_pkey')
    )
    op.create_table('_yoyo_version',
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('installed_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name='_yoyo_version_pkey')
    )
    op.create_table('yoyo_lock',
    sa.Column('locked', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('ctime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('locked', name='yoyo_lock_pkey')
    )
    op.drop_table('transactions')
    op.drop_table('avatar_history')
    op.drop_table('users')
    op.drop_table('invitations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
