"""Add description column to AcademicLibrary table

Revision ID: bdd16e39ccb7
Revises: 5f425e5a139e
Create Date: 2025-11-07 13:52:14.269718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd16e39ccb7'
down_revision = '5f425e5a139e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_libraries', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_libraries', 'description')
    # ### end Alembic commands ###
