"""add subscription_plan to user

Revision ID: c027e92508fc
Revises: bdd16e39ccb7
Create Date: 2025-11-13 21:09:21.927181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c027e92508fc'
down_revision = 'bdd16e39ccb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET subscription_plan = 'free'")
    op.alter_column('users', 'subscription_plan', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_plan')
    # ### end Alembic commands ###
