"""add_last_student_bonus_date

Revision ID: c9e12556e842
Revises: a1b2c3d4e5f6
Create Date: 2025-12-31 23:14:10.436185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e12556e842'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_student_bonus_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_student_bonus_date')
    # ### end Alembic commands ###
