"""fix_missing_phone_verified_column

Revision ID: e66d2db2f63a
Revises: 720894c0bc36
Create Date: 2025-12-24 17:51:31.330386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66d2db2f63a'
down_revision = '720894c0bc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verified')
    # ### end Alembic commands ###
