"""add preference_data table for DPO training

Revision ID: ead2a9beda23
Revises: 2026_01_17_clinical_history
Create Date: 2026-01-18 02:41:47.028173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead2a9beda23'
down_revision = '2026_01_17_clinical_history'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
