"""Add ArenaExam and user enrollment tables

Revision ID: eece5ae4aa41
Revises: fbe9e61f2036
Create Date: 2025-10-26 15:28:33.547674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eece5ae4aa41'
down_revision = 'fbe9e61f2036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('flag', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('context_filename', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arena_exams_exam_code'), 'arena_exams', ['exam_code'], unique=True)
    op.create_table('user_exam_enrollment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['arena_exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'exam_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exam_enrollment')
    op.drop_index(op.f('ix_arena_exams_exam_code'), table_name='arena_exams')
    op.drop_table('arena_exams')
    # ### end Alembic commands ###
