"""add payment_waitlist table

Revision ID: f88b341c1d2d
Revises: 9abc06438de2
Create Date: 2026-01-15 00:04:56.250676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88b341c1d2d'
down_revision = '9abc06438de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_waitlist_email'), 'payment_waitlist', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_waitlist_email'), table_name='payment_waitlist')
    op.drop_table('payment_waitlist')
    # ### end Alembic commands ###
